# This is a basic workflow to help you get started with Actions

name: GitHub Actions Maven Build Example

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Step 1 - Checkout main branch from GitHub 
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Set API token
        run: set SRCCLR_API_TOKEN=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjQzODg3LCJleHAiOjE2NDA2MzMxNTksImF1dGhvcml0aWVzIjoiQUdFTlQiLCJqdGkiOiJjMmY4ZTAzMC01NWExLTQyMGYtYTU3MS02OGIwMTFiNTA0NzAiLCJjbGllbnRfaWQiOiIiLCJzY29wZSI6W119.EXNbJMk20Eu550mplu4VWZRe8U2BDCbCG_f70F0pjgUxoO3A9jkFFYiWAgIW-HpYKKkPK3QyEryIYDhLTpnXdDx8uTKzUxWF5-2AYuOphWu9opU2LDgcdmkFCd9cFY_CMugKby-Qp9uzPswkP774_BmML_nfohGTML7mc6b4wJw

      # Runs a set of commands using the runners shell
      - name: Build maven project 
        run: mvn clean compile com.srcclr:srcclr-maven-plugin:scan
